[package]
name = "freebsd-sys"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.82" }
bitflags = { version = "2.5.0" }
proc-macro2 = { version = "1.0.82" }
quote = { version = "1.0.36" }
syn = { version = "2.0.61", features = ["full"] }
tracing = { version = "0.1.40" }
